steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/ompldr/lnd:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "us.gcr.io/ompldr/lnd:$REVISION_ID", "us.gcr.io/ompldr/lnd:latest"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "us.gcr.io/ompldr/lnd:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "us.gcr.io/ompldr/lnd:latest"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - patch
  - statefulset
  - lnd
  - --type=json
  - '-p=[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"us.gcr.io/ompldr/lnd:$REVISION_ID"}]'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ompldr-us-west1'
